export const DISCOUNT_CONSTANTS = {
  DROPDOWN_CLOSE_DELAY: 200,
  DEFAULT_COMPANIES_DISPLAY_COUNT: 10,
  MAX_PERCENTAGE_VALUE: 100,
  MAX_FLAT_AMOUNT_VALUE: 999999,
  PERCENTAGE_STEP: 1,
  FLAT_AMOUNT_STEP: 0.01
} as const;
